import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import pageStyles from '@/styles/Page.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Question 5</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={pageStyles.description}>
          <h1>Imagine a customer writes in, requesting help with the following question. Write a first response for triaging this case and helping them solve the issue.</h1>
          <h3><i>Hi there, I keep getting a build error from Vercel saying that “/vercel/path0/dist/routes-manifest.json” couldn’t be found. Can you help me debug this?? I’m so frustrated. I’ve been trying to make this work for hours and I just can’t figure it out. Your docs aren’t helpful.</i></h3>
          <p>My response would look something like:<br/><br/>"Hi,<br/><br/>Thanks so much for reahcing out, and apologies you're running into this issue.<br/><br/>Can you provide a URL of where you're seeing the error so we can investigate further?<br/><br/>If you can also provide the documentation links that you've looked for possible help, we'd love to use your feedback as a means to update and improve our docs experience for you and others."</p>
        </div>

        <div className={pageStyles.center}>
          <Link href="/question-4">&#x2190; Previous Question</Link> | <Link href="/question-6">Next Question &#x2192;</Link>
        </div>
      </main>
    </>
  )
}
