import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import pageStyles from '@/styles/Page.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Question 6</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={pageStyles.description}>
          <h1>What do you think is one of the most common problems which customers ask Vercel for help with? How would you help customers to overcome common problems, short-term and long-term?</h1>
          <p>Having used Vercel myself for personal projects, I imagine one of the most common issues that others run into is having failed builds. Even with a working local environment, I've had builds fail when deployed on Vercel. Error messages from the build logs are not always the most generous with details, so I believe cases such as those present options for both a short term and long term solution.<br/><br/>For the short term, I belive that finding a more immediate solution to their build failure would be best. That could come in form of a possible known workaround, or through a more hands on troubleshooting and testing, possibly after being raised for further investigation with the team.<br/><br/>Long term, giving the customers the ability to see better and more detailed error messages to help them help themselves, so to speak, would be optimal. Going a step further, providing them with a means, such as a external source of common errors and how to solve them, would be great. I know Vercel currently has this <a href="https://vercel.com/docs/errors" target="_blank">doc</a>, which is great. But the existing error from question 5 isn't listed, so that's an area that most likely has room for improvement!</p>
        </div>

        <div className={pageStyles.center}>
          <Link href="/question-5">&#x2190; Previous Question</Link> | <Link href="/question-7">Next Question &#x2192;</Link>
        </div>
      </main>
    </>
  )
}
