import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import pageStyles from '@/styles/Page.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Question 7</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={pageStyles.description}>
          <h1>How could we improve or alter this familiarization exercise?</h1>
          <p></p>
        </div>

        <div className={pageStyles.center}>
          <Link href="/question-6">&#x2190; Previous Question</Link>
        </div>
      </main>
    </>
  )
}
