import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import pageStyles from '@/styles/Page.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Question 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={pageStyles.description}>
          <h1>Describe how you solved a challenge that one of your previous support teams faced. How did you determine your solution was successful?</h1>
          <p>Wordpress, the chosen CMS of a vast majority of our company's clients, implemented a patch for a serious security hole they found in their codebase. Updates to our customers' websites were done manually, so many were out of date and needed to be upgraded. The team was faced with needing to update ~300 websites as quickly as possible.<br/><br/>Our manager generated a spreadsheet of the affected sites, and the team worked in tandem to individually take sites and update them before they could be exploited. The process took rougly ~2 hours each day over the course of a week.<br/><br/>No customer sites were affected, and we were able to avoid a potentially disastrous security breach. The solution was entirely a team plan and effort, and that's what ultimately led to the plan's success.</p>
        </div>

        <div className={pageStyles.center}>
          <Link href="/question-1">&#x2190; Previous Question</Link> | <Link href="/question-3">Next Question &#x2192;</Link>
        </div>
      </main>
    </>
  )
}
